import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";

import { generatePassword, withCredentials } from "./neon-bootstrap";

/**
 * Write a gitignored `.env` for the documented self-host path. Never
 * overwrites — rotate by deleting the file yourself. Secrets stay on disk,
 * not in git.
 */

const TARGET = path.resolve(".env");

function secret(): string {
  return generatePassword();
}

function main(): void {
  if (existsSync(TARGET)) {
    console.log(`${TARGET} already exists — leaving it alone`);
    return;
  }

  const postgresPassword = secret();
  const ownerPassword = secret();
  const appPassword = secret();
  const authPassword = secret();
  const authSecret = secret() + secret();

  const base = "postgres://unused@127.0.0.1:5432/spectacle";

  const body = [
    "# Generated by `pnpm self-host:init-env`. Never commit this file.",
    "# Rotate by deleting it and running the command again, then re-bootstrap.",
    "",
    "# Superuser for the compose Postgres image / one-time bootstrap only.",
    "# Not an application role. Not a fourth tenant connection string.",
    `POSTGRES_PASSWORD=${postgresPassword}`,
    `SPECTACLE_OWNER_PASSWORD=${ownerPassword}`,
    `APP_USER_PASSWORD=${appPassword}`,
    `AUTH_USER_PASSWORD=${authPassword}`,
    "",
    "# Three roles, one database. Host is loopback for the documented path",
    "# (app on this machine, Postgres published on localhost:5432).",
    `DATABASE_URL=${withCredentials(base, "app_user", appPassword)}`,
    `DATABASE_URL_OWNER=${withCredentials(base, "spectacle_owner", ownerPassword)}`,
    `AUTH_DATABASE_URL=${withCredentials(base, "auth_user", authPassword)}`,
    "",
    `BETTER_AUTH_SECRET=${authSecret}`,
    "BETTER_AUTH_URL=http://localhost:3000",
    "",
    "# Display estimate only. The database row is authoritative — see FEE-POLICY.md.",
    "PLATFORM_FEE_BPS=1000",
    "FEATURE_BROWSE=false",
    "",
  ].join("\n");

  writeFileSync(TARGET, body, { mode: 0o600 });
  console.log(`wrote ${TARGET} (mode 600). Keep it out of git.`);
}

main();
